# Generated by Django 5.1.4 on 2025-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('equipment', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('repaired', 'Repaired'), ('scrap', 'Scrap')], default='new', max_length=20)),
                ('maintenance_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive')], max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
